# Generated by Django 4.2.29 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryledger',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='issuedmaterial',
            name='product_machine_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobworkcharge',
            name='payable_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobworkdc',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobworkreceipt',
            name='new_batch_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materialsupplied',
            name='product_machine_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='outputexpected',
            name='expected_batch_suffix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnapprovaltrail',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='returnfreightcharge',
            name='freight_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnfreightcharge',
            name='payable_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnline',
            name='viability_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='returnloadingunloadingcharge',
            name='charge_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnloadingunloadingcharge',
            name='payable_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesreturnadvice',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesreturnadvice',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesreturnadvice',
            name='returned_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shiftingfreightwagedraft',
            name='expense_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shiftingfreightwagedraft',
            name='payable_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='other_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stocktransferreceipt',
            name='variance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transferfreightdetail',
            name='charge_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transferloadingunloadingwage',
            name='charge_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseshifting',
            name='other_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
