# Generated by Django 4.2.29 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bomrequest',
            name='shortfall_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of damage'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='stage',
            field=models.CharField(blank=True, default='', help_text='Production stage where damage occurred', max_length=20),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hourstask',
            name='task_description',
            field=models.CharField(blank=True, default='', help_text='Description of work performed', max_length=255),
        ),
        migrations.AlterField(
            model_name='inputconsumption',
            name='batch_used',
            field=models.CharField(blank=True, default='', help_text='Batch/lot number of consumed material', max_length=100),
        ),
        migrations.AlterField(
            model_name='issueline',
            name='batch_out',
            field=models.CharField(blank=True, default='', help_text='Batch number being issued', max_length=100),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionyieldlog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionyieldlog',
            name='variance',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Difference between planned and actual yield', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='wagevoucher',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
