# Generated by Django 4.2.29 on 2026-03-21 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCParameterLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('parameter_code', models.CharField(db_index=True, help_text='Unique parameter identifier', max_length=50, unique=True)),
                ('parameter_name', models.CharField(help_text='Human-readable parameter name', max_length=255)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., %, mg/ml, CFU/ml)', max_length=50)),
                ('acceptable_min', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum acceptable value', max_digits=15, null=True)),
                ('acceptable_max', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum acceptable value', max_digits=15, null=True)),
                ('critical_flag', models.BooleanField(db_index=True, default=False, help_text='Critical parameter affecting product release')),
                ('notes', models.TextField(blank=True)),
                ('applicable_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_parameters', to='master.product')),
                ('applicable_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_parameters', to='master.templatelibrary')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_qc_parameter_library',
                'ordering': ['parameter_code'],
            },
        ),
        migrations.CreateModel(
            name='QCRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('request_no', models.CharField(db_index=True, help_text='Auto-generated unique QC request number', max_length=50, unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requestor_role', models.CharField(help_text='Role/department of requestor', max_length=100)),
                ('batch', models.CharField(db_index=True, help_text='Batch/lot number being tested', max_length=100)),
                ('stage', models.CharField(choices=[('RECEIPT', 'Incoming/Receipt Inspection'), ('IN_PROCESS', 'In-Process Quality Check'), ('FINISHED', 'Finished Product QC'), ('SALES_RETURN', 'Sales Return QC')], db_index=True, default='FINISHED', max_length=20)),
                ('sample_photo', models.ImageField(blank=True, help_text='Photo of sample for reference', null=True, upload_to='qc_samples/%Y/%m/%d/')),
                ('sample_qty', models.DecimalField(blank=True, decimal_places=4, help_text='Quantity of sample tested', max_digits=15, null=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='REQUESTED', max_length=20)),
                ('lab_code', models.CharField(blank=True, db_index=True, help_text='Lab reference code assigned during processing', max_length=50, unique=True)),
                ('counter_sample_required', models.BooleanField(default=False, help_text='Whether counter sample should be retained')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_requests', to='master.product')),
                ('qc_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_requests', to='master.templatelibrary')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_requests', to='core.stakeholderuser')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_requests', to='core.warehouse')),
            ],
            options={
                'db_table': 'quality_qc_request',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='QCLabJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('job_no', models.CharField(db_index=True, help_text='Lab job number', max_length=50, unique=True)),
                ('sample_received_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date sample was received in lab')),
                ('results_attachment', models.FileField(blank=True, help_text='Lab result document/report', null=True, upload_to='qc_results/%Y/%m/%d/')),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='ASSIGNED', max_length=20)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_lab_jobs', to='core.stakeholderuser')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('qc_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_jobs', to='quality.qcrequest')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_qc_lab_job',
                'ordering': ['-sample_received_date'],
            },
        ),
        migrations.CreateModel(
            name='QCFinalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('report_no', models.CharField(db_index=True, help_text='Final report number', max_length=50, unique=True)),
                ('template_revision', models.IntegerField(default=1, help_text='QC template version used')),
                ('prepared_date', models.DateTimeField(auto_now_add=True)),
                ('overall_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REWORK', 'Rework Required')], db_index=True, help_text='Overall pass/fail/rework determination', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('digital_signature', models.FileField(blank=True, help_text='Digital signature of approver', null=True, upload_to='qc_signatures/%Y/%m/%d/')),
                ('attachments', models.FileField(blank=True, help_text='Additional report attachments', null=True, upload_to='qc_reports/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('distribution_list', models.ManyToManyField(blank=True, help_text='Users to whom report should be distributed', related_name='distributed_qc_reports', to='core.stakeholderuser')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_qc_reports', to='core.stakeholderuser')),
                ('qc_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='quality.qcrequest')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_qc_final_report',
                'ordering': ['-prepared_date'],
            },
        ),
        migrations.CreateModel(
            name='CounterSampleRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('storage_location', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('QC_LAB', 'QC Lab')], default='QC_LAB', help_text='Where counter sample is stored', max_length=20)),
                ('shelf', models.CharField(blank=True, help_text='Shelf/rack location', max_length=50)),
                ('bin', models.CharField(blank=True, help_text='Bin/container number', max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether return reminder has been sent')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('disposal_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_counter_sample_disposals', to='core.stakeholderuser')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_samples_issued', to='core.stakeholderuser')),
                ('qc_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_sample', to='quality.qcrequest')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_counter_sample_register',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignedParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('result_value', models.DecimalField(blank=True, decimal_places=4, help_text='Numerical test result', max_digits=15, null=True)),
                ('result_text', models.TextField(blank=True, help_text='Text description of result')),
                ('result_photo', models.ImageField(blank=True, help_text='Photo of test result', null=True, upload_to='qc_results/%Y/%m/%d/')),
                ('pass_fail', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], db_index=True, help_text='Pass/Fail determination', max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('lab_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parameters', to='quality.qclabjob')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='quality.qcparameterlibrary')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_assigned_parameter',
                'ordering': ['lab_job', 'parameter'],
            },
        ),
        migrations.CreateModel(
            name='SelectedParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('override_range_min', models.DecimalField(blank=True, decimal_places=4, help_text='Override min range for this request', max_digits=15, null=True)),
                ('override_range_max', models.DecimalField(blank=True, decimal_places=4, help_text='Override max range for this request', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_in_requests', to='quality.qcparameterlibrary')),
                ('qc_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_parameters', to='quality.qcrequest')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_selected_parameter',
                'ordering': ['qc_request', 'parameter'],
                'unique_together': {('qc_request', 'parameter')},
            },
        ),
        migrations.AddIndex(
            model_name='qcrequest',
            index=models.Index(fields=['warehouse', 'status'], name='quality_qc__warehou_3a566c_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrequest',
            index=models.Index(fields=['batch', 'product'], name='quality_qc__batch_5b7c33_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrequest',
            index=models.Index(fields=['status', 'priority'], name='quality_qc__status_9da80e_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrequest',
            index=models.Index(fields=['stage', '-request_date'], name='quality_qc__stage_23fced_idx'),
        ),
        migrations.AddIndex(
            model_name='qcparameterlibrary',
            index=models.Index(fields=['parameter_code', 'critical_flag'], name='quality_qc__paramet_9bb430_idx'),
        ),
        migrations.AddIndex(
            model_name='qcparameterlibrary',
            index=models.Index(fields=['applicable_template'], name='quality_qc__applica_5d9937_idx'),
        ),
        migrations.AddIndex(
            model_name='qcparameterlibrary',
            index=models.Index(fields=['applicable_product'], name='quality_qc__applica_f7e7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='qclabjob',
            index=models.Index(fields=['qc_request', 'analyst'], name='quality_qc__qc_requ_ad56f2_idx'),
        ),
        migrations.AddIndex(
            model_name='qclabjob',
            index=models.Index(fields=['status', '-sample_received_date'], name='quality_qc__status_af8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='qcfinalreport',
            index=models.Index(fields=['qc_request', 'overall_result'], name='quality_qc__qc_requ_f082bf_idx'),
        ),
        migrations.AddIndex(
            model_name='qcfinalreport',
            index=models.Index(fields=['overall_result', '-prepared_date'], name='quality_qc__overall_081da4_idx'),
        ),
        migrations.AddIndex(
            model_name='countersampleregister',
            index=models.Index(fields=['storage_location', 'disposal_date'], name='quality_cou_storage_34a904_idx'),
        ),
        migrations.AddIndex(
            model_name='countersampleregister',
            index=models.Index(fields=['expected_return_date'], name='quality_cou_expecte_970ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedparameter',
            index=models.Index(fields=['lab_job', 'pass_fail'], name='quality_ass_lab_job_fdf107_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedparameter',
            unique_together={('lab_job', 'parameter')},
        ),
    ]
