# Generated by Django 4.2.29 on 2026-03-21 07:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('module', models.CharField(choices=[('PURCHASE', 'Purchase Orders'), ('SALES', 'Sales Orders'), ('INVENTORY', 'Inventory'), ('FINANCE', 'Finance'), ('HR', 'Human Resources')], max_length=20)),
                ('stage', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('L1_APPROVAL', 'Level 1 Approval'), ('L2_APPROVAL', 'Level 2 Approval'), ('L3_APPROVAL', 'Level 3 Approval'), ('APPROVED', 'Final Approval'), ('REJECTED', 'Rejected')], max_length=20)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount for this approval level', max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for this approval level', max_digits=15, null=True)),
            ],
            options={
                'db_table': 'core_approval_level',
                'ordering': ['role', 'module', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('company_code', models.CharField(db_index=True, help_text='Unique company identifier', max_length=10, unique=True)),
                ('legal_name', models.CharField(help_text='Legal registered name', max_length=255)),
                ('trade_name', models.CharField(blank=True, help_text='Business name (if different from legal name)', max_length=255)),
                ('gstin', models.CharField(db_index=True, help_text='15-digit Goods and Services Tax Identification Number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')])),
                ('pan', models.CharField(db_index=True, help_text='10-character PAN', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('cin', models.CharField(blank=True, help_text='Corporate Identification Number (for companies)', max_length=21)),
                ('registered_address', models.JSONField(default=dict, help_text='Street address, city, state, country, pincode')),
                ('billing_address', models.JSONField(default=dict, help_text='Billing address details')),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('default_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('books_export_flag', models.BooleanField(default=False, help_text='Enable accounting export features')),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, help_text='Company closure/shutdown date', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'core_company',
                'ordering': ['company_code'],
            },
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('godown_code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('godown_name', models.CharField(max_length=255)),
                ('storage_condition', models.CharField(choices=[('AMBIENT', 'Ambient Temperature'), ('COLD', 'Cold Storage'), ('HAZARDOUS', 'Hazardous Materials')], max_length=20)),
                ('capacity_uom', models.CharField(choices=[('CBM', 'Cubic Meter'), ('SQM', 'Square Meter'), ('UNIT', 'Units'), ('KG', 'Kilograms')], max_length=10)),
                ('capacity_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_tracking_enabled', models.BooleanField(default=False)),
                ('default_qc_hold_area', models.BooleanField(default=False, help_text='Designate as default QC hold area')),
                ('active_flag', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_godown',
                'ordering': ['godown_code'],
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('machine_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CAPITAL_GOODS', 'Capital Goods'), ('MACHINE_SPARES', 'Machine Spares'), ('PRODUCTION_LINE', 'Production Line')], max_length=20)),
                ('commission_date', models.DateField()),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_machinery',
                'ordering': ['machine_id'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('role_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('role_name', models.CharField(max_length=255)),
                ('module_permissions', models.JSONField(default=dict, help_text='Module-wise permission mapping: {module: [action1, action2]}')),
                ('data_scope', models.CharField(choices=[('GLOBAL', 'Global Access'), ('COMPANY', 'Company Level'), ('WAREHOUSE', 'Warehouse Level')], default='COMPANY', max_length=20)),
                ('active_flag', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'core_role_definition',
                'ordering': ['role_code'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('primary_email', models.EmailField(db_index=True, max_length=254)),
                ('mobile', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_roles', models.ManyToManyField(blank=True, related_name='stakeholder_users', to='core.roledefinition')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_stakeholder_user',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('warehouse_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('FACTORY', 'Factory/Manufacturing'), ('JOB_WORK_PARTNER', 'Job Work Partner')], max_length=20)),
                ('address', models.JSONField(default=dict)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('DN', 'Dadra and Nagar Haveli'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Puducherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True)),
                ('time_zone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('default_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('active_flag', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('warehouse_coordinator_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_coordinator_warehouses', to='core.stakeholderuser')),
                ('warehouse_coordinators', models.ManyToManyField(blank=True, related_name='coordinated_warehouses', to='core.stakeholderuser')),
                ('warehouse_hr_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_coordinator_warehouses', to='core.stakeholderuser')),
                ('warehouse_managers', models.ManyToManyField(blank=True, related_name='managed_warehouses', to='core.stakeholderuser')),
                ('warehouse_supervisors', models.ManyToManyField(blank=True, related_name='supervised_warehouses', to='core.stakeholderuser')),
            ],
            options={
                'db_table': 'core_warehouse',
                'ordering': ['warehouse_code'],
            },
        ),
        migrations.AddField(
            model_name='stakeholderuser',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='core.warehouse'),
        ),
    ]
