# Generated by Django 4.2.29 on 2026-03-21 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderuser',
            name='employee_record',
            field=models.ForeignKey(blank=True, help_text='Link to HR staff record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_users', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='stakeholderuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholderuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholderuser',
            name='warehouse_scope',
            field=models.ManyToManyField(blank=True, help_text='Warehouses accessible to this user', related_name='scoped_users', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinery', to='core.godown'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='maintenance_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_machinery', to='master.vendor'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinery',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='godown',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='godown',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='godown',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='core.roledefinition'),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'active_flag'], name='core_wareho_company_12cc61_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['city', 'state'], name='core_wareho_city_f1b6d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'warehouse_code')},
        ),
        migrations.AddIndex(
            model_name='stakeholderuser',
            index=models.Index(fields=['primary_email'], name='core_stakeh_primary_5c7ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderuser',
            index=models.Index(fields=['status', 'is_active'], name='core_stakeh_status_a508c6_idx'),
        ),
        migrations.AddIndex(
            model_name='roledefinition',
            index=models.Index(fields=['data_scope', 'active_flag'], name='core_role_d_data_sc_4bd35f_idx'),
        ),
        migrations.AddIndex(
            model_name='machinery',
            index=models.Index(fields=['warehouse', 'status'], name='core_machin_warehou_06ffa5_idx'),
        ),
        migrations.AddIndex(
            model_name='machinery',
            index=models.Index(fields=['next_service_due'], name='core_machin_next_se_8691b7_idx'),
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['warehouse', 'storage_condition'], name='core_godown_warehou_155b33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='godown',
            unique_together={('warehouse', 'godown_code')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_code', 'is_active'], name='core_compan_company_99ef57_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['gstin'], name='core_compan_gstin_bc275d_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('active_to__isnull', True), ('active_to__gte', models.F('active_from')), _connector='OR'), name='company_date_range_valid'),
        ),
        migrations.AddIndex(
            model_name='approvallevel',
            index=models.Index(fields=['role', 'module'], name='core_approv_role_id_4673ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('role', 'module', 'stage')},
        ),
    ]
