# Generated by Django 4.2.29 on 2026-03-21 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict, help_text='Billing address details'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(blank=True, default='', help_text='Corporate Identification Number (for companies)', max_length=21),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, default='', help_text='15-digit Goods and Services Tax Identification Number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^(\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, db_index=True, default='', help_text='10-character PAN', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^([A-Z]{5}[0-9]{4}[A-Z]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address',
            field=models.JSONField(blank=True, default=dict, help_text='Street address, city, state, country, pincode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, default='', help_text='Business name (if different from legal name)', max_length=255),
        ),
        migrations.AlterField(
            model_name='godown',
            name='capacity_uom',
            field=models.CharField(blank=True, choices=[('CBM', 'Cubic Meter'), ('SQM', 'Square Meter'), ('UNIT', 'Units'), ('KG', 'Kilograms')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='godown',
            name='capacity_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='godown',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='godown',
            name='storage_condition',
            field=models.CharField(blank=True, choices=[('AMBIENT', 'Ambient Temperature'), ('COLD', 'Cold Storage'), ('HAZARDOUS', 'Hazardous Materials')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='commission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stakeholderuser',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stakeholderuser',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stakeholderuser',
            name='primary_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('DN', 'Dadra and Nagar Haveli'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Puducherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], default='', max_length=2),
        ),
    ]
