# Generated by Django 4.2.29 on 2026-03-21 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_active_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='15-digit Goods and Services Tax Identification Number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^(\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1})?$')]),
        ),
    ]
