# Generated by Django 4.2.29 on 2026-03-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_company_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
