# Generated by Django 4.2.29 on 2026-03-21 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('before_snapshot', models.JSONField(blank=True, help_text='State before action', null=True)),
                ('after_snapshot', models.JSONField(blank=True, help_text='State after action', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('topic', models.CharField(db_index=True, max_length=200)),
                ('decision_details', models.TextField()),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_actions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('parameter_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parameter_value', models.TextField()),
                ('module_scope', models.CharField(choices=[('GLOBAL', 'Global'), ('HR', 'HR'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('FINANCE', 'Finance'), ('WORKFLOW', 'Workflow')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parameter_name'],
            },
        ),
    ]
