# Generated by Django 4.2.29 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonentry',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comparisonentry',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comparisonentry',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispatchetaupdate',
            name='expected_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchetaupdate',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evalapprovaltrail',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freightadviceinbound',
            name='destination_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freightadviceinbound',
            name='quantity_uom',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='freightdetail',
            name='destination_state',
            field=models.CharField(blank=True, default='', help_text='For tax calculation', max_length=100),
        ),
        migrations.AlterField(
            model_name='freightdetail',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freightdetail',
            name='quantity_uom',
            field=models.CharField(blank=True, default='', help_text='UOM for freight calculation', max_length=10),
        ),
        migrations.AlterField(
            model_name='loadingunloadingwage',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='poetaupdate',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poetaupdate',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='poline',
            name='batch_requirement_notes',
            field=models.TextField(blank=True, default='', help_text='Special batch/lot requirements'),
        ),
        migrations.AlterField(
            model_name='poline',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description'),
        ),
        migrations.AlterField(
            model_name='prapprovaltrail',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prline',
            name='description_override',
            field=models.TextField(blank=True, default='', help_text='Override product description if needed'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='freight_terms',
            field=models.CharField(blank=True, default='', help_text='e.g., FOB, CIF, DDP', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, default='', help_text='e.g., Net 30, Net 60', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Standard T&C and special conditions'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True, default='', help_text='Business justification for the purchase'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requestor_role',
            field=models.CharField(blank=True, default='', help_text='Role of the requestor (cached for audit trail)', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteevaluation',
            name='justification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='delivery_timeline',
            field=models.PositiveIntegerField(blank=True, help_text='Days from order placement', null=True),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='specification',
            field=models.TextField(blank=True, default='', help_text="Vendor's specification/variation"),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='delivery_terms',
            field=models.CharField(blank=True, default='', help_text='e.g., 15 days, immediate', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='freight_terms',
            field=models.CharField(blank=True, default='', help_text='e.g., FOB, CIF, DDP', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days from order to delivery', null=True),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='payment_terms',
            field=models.CharField(blank=True, default='', help_text='e.g., Net 30, COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='price_valid_till',
            field=models.DateField(blank=True, help_text='Quote validity date', null=True),
        ),
        migrations.AlterField(
            model_name='quoteresponse',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receiptadvice',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='receiptadvice',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receiptadvice',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', help_text='Vehicle registration number', max_length=50),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfqheader',
            name='skip_rfq_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorpaymentadvice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
