# Generated by Django 4.2.29 on 2026-03-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_gstin'),
        ('purchase', '0004_alter_rfqheader_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who created the PR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_created', to='core.stakeholderuser'),
        ),
    ]
