# Generated by Django 4.2.29 on 2026-03-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchaserequest_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteline',
            name='pr_line',
            field=models.ForeignKey(blank=True, help_text='Referenced PR line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='purchase.prline'),
        ),
    ]
