# Generated by Django 4.2.29 on 2026-03-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_gstin'),
        ('purchase', '0006_alter_quoteline_pr_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_evaluations', to='core.stakeholderuser'),
        ),
    ]
