# Generated by Django 4.2.29 on 2026-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_quoteevaluation_evaluated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptadvice',
            name='linked_pos',
            field=models.ManyToManyField(blank=True, related_name='receipt_advices', to='purchase.purchaseorder'),
        ),
    ]
