# Generated by Django 4.2.29 on 2026-03-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_gstin'),
        ('purchase', '0008_alter_receiptadvice_linked_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightadviceinbound',
            name='actual_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_freight_advices', to='core.stakeholderuser'),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='delivery_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='driver_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='freight_terms',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('TO_PAY', 'To Pay')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='lorry_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freightadviceinbound',
            name='transport_document_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freightadviceinbound',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
