# Generated by Django 4.2.29 on 2026-03-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_gstin'),
        ('purchase', '0009_freight_advice_enhanced_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightadviceinbound',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stakeholderuser'),
        ),
    ]
