# Generated by Django 4.2.29 on 2026-03-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('purchase', '0010_alter_freightadviceinbound_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightadviceinbound',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_advices_inbound', to='master.transporter'),
        ),
    ]
