# Generated by Django 4.2.29 on 2026-03-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('purchase', '0011_alter_freightadviceinbound_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='master.transporter'),
        ),
    ]
