# Generated by Django 4.2.29 on 2026-03-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_gstin'),
        ('purchase', '0012_purchaseorder_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='godown_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_items', to='core.godown'),
        ),
    ]
