# Generated by Django 4.2.29 on 2026-03-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('purchase', '0013_alter_receiptline_godown_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightdetail',
            name='transporter',
            field=models.ForeignKey(blank=True, help_text='Transporter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_details', to='master.transporter'),
        ),
    ]
