# Generated by Django 4.2.29 on 2026-03-26 09:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0015_vendorpaymentadvice_bill_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('bill_no', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('vendor_invoice_no', models.CharField(blank=True, default='', help_text="Vendor's own invoice number", max_length=100)),
                ('bill_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.purchaseorder')),
                ('receipt_advice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.receiptadvice')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='master.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bill',
                'verbose_name_plural': 'Vendor Bills',
                'db_table': 'purchase_vendor_bill',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('credit_no', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('credit_date', models.DateField(db_index=True)),
                ('credit_type', models.CharField(choices=[('CREDIT', 'Credit Note'), ('DEBIT', 'Debit Note')], default='CREDIT', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('APPLIED', 'Applied'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='purchase.vendorbill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credits', to='master.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Credit',
                'verbose_name_plural': 'Vendor Credits',
                'db_table': 'purchase_vendor_credit',
                'ordering': ['-credit_date'],
            },
        ),
        migrations.AlterField(
            model_name='vendorpaymentadvice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='VendorCreditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to='purchase.vendorcredit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credit_lines', to='master.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Credit Line',
                'verbose_name_plural': 'Vendor Credit Lines',
                'db_table': 'purchase_vendor_credit_line',
                'ordering': ['credit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_lines', to='purchase.vendorbill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='master.product')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Bill Line',
                'verbose_name_plural': 'Vendor Bill Lines',
                'db_table': 'purchase_vendor_bill_line',
                'ordering': ['bill', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('payment_no', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_mode', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], default='BANK_TRANSFER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchase.vendorbill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='master.vendor')),
            ],
            options={
                'verbose_name': 'Payment Made',
                'verbose_name_plural': 'Payments Made',
                'db_table': 'purchase_payment_made',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorcredit',
            index=models.Index(fields=['vendor', 'status'], name='purchase_ve_vendor__adf6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcredit',
            index=models.Index(fields=['status', '-credit_date'], name='purchase_ve_status_5bcced_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['vendor', 'status'], name='purchase_ve_vendor__f1a64c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status', '-bill_date'], name='purchase_ve_status_897e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmade',
            index=models.Index(fields=['vendor', 'status'], name='purchase_pa_vendor__abe3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmade',
            index=models.Index(fields=['status', '-payment_date'], name='purchase_pa_status_11299e_idx'),
        ),
    ]
