# Generated by Django 4.2.29 on 2026-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_add_vendor_bills_payments_made_vendor_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcredit',
            name='credit_type',
            field=models.CharField(choices=[('CREDIT', 'Credit Note'), ('DEBIT', 'Debit Note'), ('ADVANCE', 'Advance Payment')], default='CREDIT', max_length=20),
        ),
    ]
