# Generated by Django 4.2.29 on 2026-03-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_alter_vendorcredit_credit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='po_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='purchase.poline'),
        ),
    ]
