# Generated by Django 4.2.29 on 2026-03-30 05:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_change_receipt_line_po_line_to_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightdetail',
            name='tentative_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loadingunloadingwage',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
