# Generated by Django 4.2.29 on 2026-03-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('purchase', '0019_add_defaults_freight_wage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master.vendor'),
        ),
    ]
