# Generated by Django 4.2.29 on 2026-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_make_po_vendor_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='allow_rfq_skip',
            field=models.BooleanField(default=False, help_text='If True, approval creates PO directly instead of RFQ'),
        ),
    ]
