# Generated by Django 4.2.29 on 2026-04-01 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('purchase', '0021_add_allow_rfq_skip_to_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Preferred vendor for direct PO creation (used with RFQ skip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='master.vendor'),
        ),
    ]
