# Generated by Django 4.2.29 on 2026-04-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0022_add_preferred_vendor_to_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('module', models.CharField(choices=[('PR', 'Purchase Request'), ('RFQ', 'RFQ'), ('QUOTE', 'Quote Response'), ('EVALUATION', 'Evaluation'), ('PO', 'Purchase Order'), ('RECEIPT', 'Receipt Advice'), ('FREIGHT', 'Freight'), ('BILL', 'Vendor Bill'), ('PAYMENT', 'Payment Made'), ('CREDIT', 'Vendor Credit')], db_index=True, max_length=20)),
                ('record_id', models.UUIDField(db_index=True, help_text='ID of the related record')),
                ('file', models.FileField(upload_to='purchase/attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Attachment',
                'verbose_name_plural': 'Purchase Attachments',
                'db_table': 'purchase_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
