# Generated by Django 4.2.29 on 2026-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_add_purchase_attachment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmade',
            name='payment_mode',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('ADVANCE', 'Advance'), ('CREDIT', 'Credit')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
