# Generated by Django 4.2.29 on 2026-03-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_create_default_template'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emaillog',
            name='comm_email__is_acti_log_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailtemplate',
            name='comm_email__is_acti_tmpl_idx',
        ),
    ]
