# Generated by Django 4.2.29 on 2026-03-21 07:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parser_type', models.CharField(choices=[('CUSTOMER_PO', 'Customer Purchase Order'), ('BANK_STATEMENT', 'Bank Statement'), ('INVOICE', 'Invoice')], max_length=50)),
                ('llm_provider', models.CharField(choices=[('OLLAMA', 'Ollama'), ('GEMINI', 'Google Gemini'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic Claude')], max_length=50)),
                ('llm_model', models.CharField(help_text="e.g., 'mistral:latest', 'gemini-1.5-pro'", max_length=100)),
                ('prompt_template', models.TextField()),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=0.8, help_text='Minimum confidence score (0-1) to accept parsing result', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parser_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('input_file', models.FileField(upload_to='parser/inputs/')),
                ('ocr_text', models.TextField(help_text='Raw OCR output')),
                ('llm_response', models.JSONField(help_text='Structured LLM output')),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('parsed_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='ai_parser.parserconfiguration')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['configuration', 'created_at'], name='ai_parser_p_configu_f1082d_idx'), models.Index(fields=['parsed_successfully', 'created_at'], name='ai_parser_p_parsed__e90a5b_idx')],
            },
        ),
    ]
