# Generated by Django 4.2.29 on 2026-03-21 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoupload',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='parsed_po_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='review_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dcline',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatchchallan',
            name='driver_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchchallan',
            name='lorry_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='freightadviceoutbound',
            name='destination_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freightadviceoutbound',
            name='quantity_uom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedline',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receivableledger',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('NOT_DUE', 'Not Due'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='NOT_DUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='credit_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='soline',
            name='batch_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='soline',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
