# Generated by Django 4.2.29 on 2026-03-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('sales', '0002_alter_customerpoupload_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='master.pricelist'),
        ),
    ]
