# Generated by Django 4.2.29 on 2026-03-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_make_price_list_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
