# Generated by Django 4.2.29 on 2026-03-31 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_so_dispatch_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcline',
            name='noa',
            field=models.IntegerField(blank=True, help_text='Number of Articles/Packages', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dispatchchallan',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchchallan',
            name='invoice_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
