# Generated by Django 4.2.29 on 2026-03-31 09:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_add_dc_invoice_noa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='additional_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='freight_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='freight_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='less_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='lorry_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='tds_less',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='unloading_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freightadviceoutbound',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='FreightAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('attachment_type', models.CharField(choices=[('OUTWARD_GATEPASS', 'Outward Gatepass'), ('FREIGHT_LETTER', 'Freight Letter'), ('IMAGE', 'Image'), ('PDF', 'PDF Attachment'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='freight/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.freightadviceoutbound')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['freight', 'attachment_type'],
            },
        ),
        migrations.CreateModel(
            name='FreightPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('payment_date', models.DateField(db_index=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('OTHER', 'Other')], max_length=20)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.freightadviceoutbound')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['freight', 'payment_date'],
                'indexes': [models.Index(fields=['freight', 'payment_date'], name='sales_freig_freight_bd0ae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreightDCLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_links', to='sales.dispatchchallan')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_links', to='sales.freightadviceoutbound')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['freight', 'created_at'],
                'unique_together': {('freight', 'dc')},
            },
        ),
    ]
