# Generated by Django 4.2.29 on 2026-03-31 09:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_stakeholderuser_user'),
        ('master', '0004_add_preferred_vendors_to_product'),
        ('sales', '0006_add_outward_freight_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFreightDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('freight_no', models.CharField(db_index=True, help_text='Auto-generated Freight Detail number', max_length=50, unique=True)),
                ('freight_date', models.DateField(db_index=True)),
                ('freight_type', models.CharField(blank=True, choices=[('FULL_LOAD', 'Full Load'), ('PART_LOAD', 'Part Load'), ('LOCAL', 'Local'), ('EXPRESS', 'Express')], default='', max_length=20)),
                ('lorry_no', models.CharField(blank=True, default='', max_length=50)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_uom', models.CharField(blank=True, default='MTS', max_length=20)),
                ('freight_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('freight_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_freight', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('destination_state', models.CharField(blank=True, default='', max_length=100)),
                ('decision_box', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_details', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freight_details', to='master.customer')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_details', to='core.warehouse')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_freight_details', to='master.transporter')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_freight_detail',
                'ordering': ['-freight_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightDetailDCLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_detail_links', to='sales.dispatchchallan')),
                ('freight_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_links', to='sales.salesfreightdetail')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['freight_detail', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='freightadviceoutbound',
            name='freight_detail',
            field=models.ForeignKey(blank=True, help_text='Link to Freight Detail parent entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_freights', to='sales.salesfreightdetail'),
        ),
        migrations.AddIndex(
            model_name='salesfreightdetail',
            index=models.Index(fields=['company', '-freight_date'], name='sales_freig_company_de5be5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfreightdetail',
            index=models.Index(fields=['status', '-freight_date'], name='sales_freig_status_c4f256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='freightdetaildclink',
            unique_together={('freight_detail', 'dc')},
        ),
    ]
