# Generated by Django 4.2.29 on 2026-03-31 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('sales', '0007_add_sales_freight_detail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freightdetaildclink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='freightdetaildclink',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_detail_links', to='master.product'),
        ),
        migrations.AddField(
            model_name='freightdetaildclink',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
