# Generated by Django 4.2.29 on 2026-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_product_qty_to_freight_dc_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='destination',
            field=models.CharField(blank=True, default='', help_text='Delivery destination', max_length=255),
        ),
    ]
