# Generated by Django 4.2.29 on 2026-04-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stakeholderuser_user'),
        ('sales', '0009_add_destination_to_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoupload',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_pos', to='core.company'),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Customer PO number', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_pos', to='core.warehouse'),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='po_uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CONVERTED', 'Converted to Sales Order'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='upload_id',
            field=models.CharField(db_index=True, help_text='Auto-generated Customer PO number', max_length=50, unique=True),
        ),
    ]
