# Generated by Django 4.2.29 on 2026-04-01 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
        ('sales', '0010_restructure_customer_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoupload',
            name='credit_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='freight_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_pos', to='master.pricelist'),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='required_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='delivery_schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='line_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
