# Generated by Django 4.2.29 on 2026-04-01 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_so_fields_to_customer_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoupload',
            name='carrier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='delivery_type',
            field=models.CharField(blank=True, default='', help_text='ex-factory, door delivery, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='indent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='indent_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='insurance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='receiving_branch',
            field=models.TextField(blank=True, default='', help_text='Receiving Branch / Billing Address'),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='hsn_code',
            field=models.CharField(blank=True, default='', help_text='HSN/SAC Code', max_length=20),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parsedline',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total GST % (SGST + CGST)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
