# Generated by Django 4.2.29 on 2026-04-01 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_po_document_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoupload',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='consignee_address',
            field=models.TextField(blank=True, default='', help_text='Ship to address with GSTIN'),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='consignee_name',
            field=models.CharField(blank=True, default='', help_text='Ship to name', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='dealer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='dealer_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='dealer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='delivery_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='dispatched_through',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='party_code',
            field=models.CharField(blank=True, default='', help_text='Supplier/Party code from customer system', max_length=50),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='price_basis',
            field=models.CharField(blank=True, default='', help_text='CIF, FOB, Ex-Factory, C&F', max_length=50),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='sales_order_ref',
            field=models.CharField(blank=True, default='', help_text="Customer's Sales Order reference", max_length=100),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IGST % for inter-state', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='parsedline',
            name='item_code',
            field=models.CharField(blank=True, default='', help_text="Customer's item code", max_length=50),
        ),
    ]
