# Generated by Django 4.2.29 on 2026-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_add_all_po_sample_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpoupload',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='credit_terms',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='dealer_address',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='dealer_gstin',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='dealer_name',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='price_basis',
        ),
        migrations.RemoveField(
            model_name='customerpoupload',
            name='receiving_branch',
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='consignee_address',
            field=models.TextField(blank=True, default='', help_text='Ship to address - auto-filled from customer'),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='consignee_name',
            field=models.CharField(blank=True, default='', help_text='Ship to name - auto-filled from customer', max_length=255),
        ),
    ]
