# Generated by Django 4.2.29 on 2026-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_unwanted_po_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_pos',
            field=models.ManyToManyField(blank=True, help_text='Multiple Customer POs linked to this SO', related_name='linked_sales_orders', to='sales.customerpoupload'),
        ),
    ]
