# Generated by Django 4.2.29 on 2026-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_add_m2m_customer_pos_to_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoupload',
            name='billing_address',
            field=models.TextField(blank=True, default='', help_text='Company billing address'),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpoupload',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
