# Generated by Django 4.2.29 on 2026-04-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_add_consignee_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightadviceoutbound',
            name='dispatch_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_advices', to='sales.dispatchchallan'),
        ),
    ]
