# Generated by Django 4.2.29 on 2026-04-02 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_make_dispatch_challan_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfreightdetail',
            name='additional_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salesfreightdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salesfreightdetail',
            name='less_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salesfreightdetail',
            name='tds_less',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
