# Generated by Django 4.2.29 on 2026-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_add_cost_fields_to_freight_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='additional_freight',
        ),
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='less_amount',
        ),
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='tds_less',
        ),
    ]
