# Generated by Django 4.2.29 on 2026-04-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remove_cost_fields_from_outward_freight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='loading_wages_amount',
        ),
    ]
