# Generated by Django 4.2.29 on 2026-04-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0004_add_preferred_vendors_to_product'),
        ('core', '0005_alter_stakeholderuser_user'),
        ('sales', '0020_remove_loading_wages_from_outward_freight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('sl_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('hsn_sac', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'ordering': ['sl_no'],
            },
        ),
        migrations.RemoveIndex(
            model_name='salesinvoicecheck',
            name='sales_sales_dc_refe_2ccc27_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinvoicecheck',
            name='sales_sales_varianc_61f2f9_idx',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='acceptance_timestamp',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='invoice_check_id',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='statutory_invoice_upload',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='total_value_so',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='total_value_upload',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='variance_amount',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='variance_flag',
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='amount_in_words',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyer_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyer_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyer_state_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyers_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='buyers_order_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='cgst_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.company'),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_bank_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_bank_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_pan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='company_state_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='consignee_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='consignee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='consignee_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='consignee_state_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='master.customer'),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='declaration',
            field=models.TextField(blank=True, default='We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.'),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='delivery_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='dispatch_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='dispatch_doc_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='dispatched_through',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='igst_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='invoice_no',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='other_references',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate'), ('NET15', 'Net 15 Days'), ('NET30', 'Net 30 Days'), ('NET45', 'Net 45 Days'), ('NET60', 'Net 60 Days'), ('CUSTOM', 'Custom')], default='NET30', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='sgst_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='so_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoicecheck',
            name='terms_of_delivery',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='dc_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_checks', to='sales.dispatchchallan'),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='salesinvoicecheck',
            index=models.Index(fields=['customer', '-invoice_date'], name='sales_invoi_custome_311f14_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicecheck',
            index=models.Index(fields=['status', '-invoice_date'], name='sales_invoi_status_51a40a_idx'),
        ),
        migrations.AlterModelTable(
            name='salesinvoicecheck',
            table='sales_invoice',
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='sales.salesinvoicecheck'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='master.product'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
