# Generated by Django 4.2.29 on 2026-04-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_restructure_sales_invoice_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='company_bank_account',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='company_bank_branch',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='company_bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='salesinvoicecheck',
            name='company_bank_name',
        ),
    ]
