# Generated by Django 4.2.29 on 2026-04-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_bank_fields_from_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='consignee_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='consignee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_terms',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dispatched_through',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='indent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='indent_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='party_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
