# Generated by Django 4.2.29 on 2026-04-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_add_cpo_fields_to_sales_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightadviceoutbound',
            name='dispatch_challan',
        ),
    ]
