# Generated by Django 4.2.29 on 2026-04-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_remove_dispatch_challan_from_outward_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoupload',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customerpoupload',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='salesinvoicecheck',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='billing_gstin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='consignee_gstin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
