# Generated by Django 4.2.29 on 2026-03-21 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='freight_split_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^(\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^([A-Z]{5}[0-9]{4}[A-Z]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='priceline',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='default_freight_terms',
            field=models.CharField(blank=True, choices=[('PAID', 'Freight Paid'), ('TO_COLLECT', 'Freight To Collect'), ('MIXED', 'Mixed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='delivery_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_notes',
            field=models.TextField(blank=True, default='', help_text='Notes on unit conversion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='freight_class',
            field=models.CharField(blank=True, default='', help_text='Freight classification for logistics', max_length=50),
        ),
        migrations.AlterField(
            model_name='secondaryuom',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecatalogue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='delivery_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='applicable_on',
            field=models.JSONField(blank=True, default=list, help_text='Product categories, service types, or transaction types'),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='taxmaster',
            name='section_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='templateapprovallog',
            name='change_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='templateapprovallog',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='templatelibrary',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatelibrary',
            name='layout_json',
            field=models.JSONField(blank=True, default=dict, help_text='Template layout and field configuration'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='freight_modes',
            field=models.JSONField(blank=True, default=list, help_text='Available modes: ROAD, RAIL, AIR, SHIP, COURIER'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^(\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='freight_split_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format', regex='^(\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid PAN format', regex='^([A-Z]{5}[0-9]{4}[A-Z]{1})?$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.JSONField(blank=True, default=list, help_text='Multi-select: MATERIAL, SERVICE, FREIGHT, WAGES, JOB_WORK, CONTRACTOR'),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='^([A-Z]{4}0[A-Z0-9]{6})?$')]),
        ),
    ]
