# Generated by Django 4.2.29 on 2026-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_preferred_vendors_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceline',
            name='uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Liters'), ('MTR', 'Meters'), ('SQM', 'Square Meter'), ('CUM', 'Cubic Meter'), ('BOX', 'Box'), ('PACK', 'Pack'), ('MTS', 'Metric Ton')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Liters'), ('MTR', 'Meters'), ('SQM', 'Square Meter'), ('CUM', 'Cubic Meter'), ('BOX', 'Box'), ('PACK', 'Pack'), ('MTS', 'Metric Ton')], max_length=10),
        ),
        migrations.AlterField(
            model_name='secondaryuom',
            name='to_uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LTR', 'Liters'), ('MTR', 'Meters'), ('SQM', 'Square Meter'), ('CUM', 'Cubic Meter'), ('BOX', 'Box'), ('PACK', 'Pack'), ('MTS', 'Metric Ton')], max_length=10),
        ),
    ]
